<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d3yii2\d3labels\models\base;

use Yii;
use yii\db\ActiveQuery;
use yii\db\ActiveRecord;
use yii\db\Exception;

/**
 * This is the base-model class for table "d3_label_history".
 *
 * @property string $id
 * @property integer $definition_id
 * @property string $model_record_id
 * @property string $action
 * @property string $model_id
 * @property string $time
 * @property integer $user_id
 *
 * @property \d3yii2\d3labels\models\D3lDefinition $definition
 * @property string $aliasModel
 */
abstract class D3LabelHistory extends ActiveRecord
{


    /**
     * ENUM field values
     */
    public const ACTION_ADDED = 'Added';
    public const ACTION_DROPED = 'Droped';
    public const ACTION_CANCELED = 'Canceled';
    public const ACTION_EXPLODED = 'Exploded';
    public $enum_labels = false;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'd3_label_history';
    }

    /**
     * get column action enum value label
     * @param string $value
     * @return string
     */
    public static function getActionValueLabel($value): string
    {
        $labels = self::optsAction();
        return $labels[$value] ?? $value;
    }

    /**
     * column action ENUM value labels
     * @return array
     */
    public static function optsAction()
    {
        return [
            self::ACTION_ADDED => Yii::t('d3labels', self::ACTION_ADDED),
            self::ACTION_DROPED => Yii::t('d3labels', self::ACTION_DROPED),
            self::ACTION_CANCELED => Yii::t('d3labels', self::ACTION_CANCELED),
            self::ACTION_EXPLODED => Yii::t('d3labels', self::ACTION_EXPLODED),
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['definition_id', 'model_record_id', 'action', 'model_id'], 'required'],
            [['definition_id', 'model_record_id', 'model_id', 'user_id'], 'integer'],
            [['action'], 'string'],
            [['time'], 'safe'],
            [
                ['definition_id'],
                'exist',
                'skipOnError' => true,
                'targetClass' => \d3yii2\d3labels\models\D3lDefinition::className(),
                'targetAttribute' => ['definition_id' => 'id']
            ],
            [
                'action',
                'in',
                'range' => [
                    self::ACTION_ADDED,
                    self::ACTION_DROPED,
                    self::ACTION_CANCELED,
                    self::ACTION_EXPLODED,
                ]
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('d3labels', 'ID'),
            'definition_id' => Yii::t('d3labels', 'Definition ID'),
            'model_record_id' => Yii::t('d3labels', 'Model Record ID'),
            'action' => Yii::t('d3labels', 'Action'),
            'model_id' => Yii::t('d3labels', 'Model ID'),
            'time' => Yii::t('d3labels', 'Time'),
            'user_id' => Yii::t('d3labels', 'User ID'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'definition_id' => Yii::t('d3labels', 'Definition'),
            'model_record_id' => Yii::t('d3labels', 'Model record'),
            'action' => Yii::t('d3labels', 'Action'),
            'model_id' => Yii::t('d3labels', 'Label/Time Bomb record'),
            'time' => Yii::t('d3labels', 'Time'),
            'user_id' => Yii::t('d3labels', 'User'),
        ]);
    }

    /**
     * @return ActiveQuery
     */
    public function getDefinition()
    {
        return $this->hasOne(\d3yii2\d3labels\models\D3lDefinition::className(), ['id' => 'definition_id']);
    }

    /**
     * @param bool $runValidation
     * @param null $attributeNames
     * @throws Exception
     */
    public function saveOrException($runValidation = true, $attributeNames = null): void
    {
        if (!$this->save($runValidation, $attributeNames)) {
            throw new Exception(json_encode($this->getErrors()));
        }
    }
}
