<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d3yii2\d3labels\models\base;

use Yii;
use yii\db\ActiveQuery;
use yii\db\ActiveRecord;
use yii\db\Exception;

/**
 * This is the base-model class for table "d3l_time_bomb".
 *
 * @property string $id
 * @property integer $definition_id
 * @property string $record_id
 * @property string $explode_time
 * @property string $status
 *
 * @property \d3yii2\d3labels\models\D3lDefinition $definition
 * @property string $aliasModel
 */
abstract class D3lTimeBomb extends ActiveRecord
{


    /**
     * ENUM field values
     */
    public const STATUS_ACTIVE = 'Active';
    public const STATUS_CANCELED = 'Canceled';
    public const STATUS_EXPLODED = 'Exploded';
    public $enum_labels = false;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'd3l_time_bomb';
    }

    /**
     * get column status enum value label
     * @param string $value
     * @return string
     */
    public static function getStatusValueLabel($value): string
    {
        $labels = self::optsStatus();
        return $labels[$value] ?? $value;
    }

    /**
     * column status ENUM value labels
     * @return array
     */
    public static function optsStatus()
    {
        return [
            self::STATUS_ACTIVE => Yii::t('d3labels', self::STATUS_ACTIVE),
            self::STATUS_CANCELED => Yii::t('d3labels', self::STATUS_CANCELED),
            self::STATUS_EXPLODED => Yii::t('d3labels', self::STATUS_EXPLODED),
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['definition_id', 'record_id'], 'required'],
            [['definition_id', 'record_id'], 'integer'],
            [['explode_time'], 'safe'],
            [['status'], 'string'],
            [
                ['definition_id'],
                'exist',
                'skipOnError' => true,
                'targetClass' => \d3yii2\d3labels\models\D3lDefinition::className(),
                'targetAttribute' => ['definition_id' => 'id']
            ],
            [
                'status',
                'in',
                'range' => [
                    self::STATUS_ACTIVE,
                    self::STATUS_CANCELED,
                    self::STATUS_EXPLODED,
                ]
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('d3labels', 'ID'),
            'definition_id' => Yii::t('d3labels', 'Definition ID'),
            'record_id' => Yii::t('d3labels', 'Record ID'),
            'explode_time' => Yii::t('d3labels', 'Explode Time'),
            'status' => Yii::t('d3labels', 'Status'),
        ];
    }

    /**
     * @return ActiveQuery
     */
    public function getDefinition()
    {
        return $this->hasOne(\d3yii2\d3labels\models\D3lDefinition::className(), ['id' => 'definition_id']);
    }

    /**
     * @param bool $runValidation
     * @param null $attributeNames
     * @throws Exception
     */
    public function saveOrException($runValidation = true, $attributeNames = null): void
    {
        if (!$this->save($runValidation, $attributeNames)) {
            throw new Exception(json_encode($this->getErrors()));
        }
    }
}
