<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d3yii2\d3labels\models\base;

use Yii;
use yii\db\Exception;

/**
 * This is the base-model class for table "d3l_time_bomb".
 *
 * @property string $id
 * @property integer $definition_id
 * @property string $record_id
 * @property string $explode_time
 * @property string $status
 *
 * @property \d3yii2\d3labels\models\D3lDefinition $definition
 * @property string $aliasModel
 */
abstract class D3lTimeBomb extends \yii\db\ActiveRecord
{



    /**
    * ENUM field values
    */
    const STATUS_ACTIVE = 'Active';
    const STATUS_CANCELED = 'Canceled';
    const STATUS_EXPLODED = 'Exploded';
    var $enum_labels = false;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'd3l_time_bomb';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['definition_id', 'record_id'], 'required'],
            [['definition_id', 'record_id'], 'integer'],
            [['explode_time'], 'safe'],
            [['status'], 'string'],
            [['definition_id'], 'exist', 'skipOnError' => true, 'targetClass' => \d3yii2\d3labels\models\D3lDefinition::className(), 'targetAttribute' => ['definition_id' => 'id']],
            ['status', 'in', 'range' => [
                    self::STATUS_ACTIVE,
                    self::STATUS_CANCELED,
                    self::STATUS_EXPLODED,
                ]
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('d3labels', 'ID'),
            'definition_id' => Yii::t('d3labels', 'Definition ID'),
            'record_id' => Yii::t('d3labels', 'Record ID'),
            'explode_time' => Yii::t('d3labels', 'Explode Time'),
            'status' => Yii::t('d3labels', 'Status'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDefinition()
    {
        return $this->hasOne(\d3yii2\d3labels\models\D3lDefinition::className(), ['id' => 'definition_id']);
    }





    /**
     * get column status enum value label
     * @param string $value
     * @return string
     */
    public static function getStatusValueLabel($value){
        $labels = self::optsStatus();
        if(isset($labels[$value])){
            return $labels[$value];
        }
        return $value;
    }

    /**
     * column status ENUM value labels
     * @return array
     */
    public static function optsStatus()
    {
        return [
            self::STATUS_ACTIVE => Yii::t('d3labels', self::STATUS_ACTIVE),
            self::STATUS_CANCELED => Yii::t('d3labels', self::STATUS_CANCELED),
            self::STATUS_EXPLODED => Yii::t('d3labels', self::STATUS_EXPLODED),
        ];
    }
    public function saveOrException($runValidation = true, $attributeNames = null)
    {
        if(!parent::save($runValidation, $attributeNames)){
            throw new Exception(json_encode($this->getErrors()));
        }
    }
}
