<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d3yii2\d3labels\models\base;

use Yii;
use d3system\behaviors\D3DateTimeBehavior;
use yii\db\Exception;

/**
 * This is the base-model class for table "d3l_notes".
 *
 * @property integer $id
 * @property integer $model_id
 * @property integer $model_record_id
 * @property string $notes
 * @property integer $user_id
 * @property string $time
 *
 * @property \d3yii2\d3labels\models\SysModels $model
 * @property string $aliasModel
 */
abstract class D3Note extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName(): string
    {
        return 'd3l_notes';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = [
        ];
        $behaviors = array_merge(
            $behaviors,
            D3DateTimeBehavior::getConfig(['time'])
        );
        return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            'required' => [['model_id', 'model_record_id'], 'required'],
            'tinyint Unsigned' => [['model_id'],'integer' ,'min' => 0 ,'max' => 255],
            'integer Unsigned' => [['id','model_record_id','user_id'],'integer' ,'min' => 0 ,'max' => 4294967295],
            [['time'], 'safe'],
            [['notes'], 'string', 'max' => 255],
            [['model_id'], 'exist', 'skipOnError' => true, 'targetClass' => \d3yii2\d3labels\models\SysModels::class, 'targetAttribute' => ['model_id' => 'id']],
            'D3DateTimeBehavior' => [['time_local'],'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('d3labels', 'ID'),
            'model_id' => Yii::t('d3labels', 'Model ID'),
            'model_record_id' => Yii::t('d3labels', 'Model Record ID'),
            'notes' => Yii::t('d3labels', 'Notes'),
            'user_id' => Yii::t('d3labels', 'User ID'),
            'time' => Yii::t('d3labels', 'Time'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getModel()
    {
        return $this->hasOne(\d3yii2\d3labels\models\SysModels::class, ['id' => 'model_id'])->inverseOf('d3lNotes');
    }


    /**
     * @param bool $runValidation
     * @param null $attributeNames
     * @throws Exception
     */
    public function saveOrException($runValidation = true, $attributeNames = null): void
    {
        if (!$this->save($runValidation, $attributeNames)) {
            throw new Exception(json_encode($this->getErrors()));
        }
    }
}
