<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Action' => 'Darbība',
    'Attached Labels' => 'Piesaistītās birkas',
    'Attach Label' => 'Pievienot birku',
    'Cancel and close' => 'Atcelt un aizvērt',
    'Create Label' => 'Izveidot birku',
    'Collor' => 'Krāsa',
    'Cannot delete.  Attached to records' => 'Nav iespējams dzēst. Šī birka ir piesaistīta ierakstiem',
    'Deleted sucessfully' => 'Veiksmīgi dzēsta',
    'Not exists or deleted already' => 'Neeksistē vai jau ir dzēsta',
    'Filter by Label' => 'Atlasīt pēc birkas',
    'Icon' => 'Ikona',
    'Labels created successfully' => 'Birka izveidota',
    'Label' => 'Nosaukums',
    'Label attached' => 'Birka piesaistīta',
    'Label definition record not exists' => 'Birkas definīcijas ieraksts neeksistē',
    'Label is required if no icon' => 'Ir nepieciešams nosaukums, ja nav uzdota ikona',
    'Label will be deleted' => 'Birka tiks dzēsta',
    'Labels' => 'Birkas',
    'Look' => 'Izskats',
    'Remove' => 'Noņemt',
    'Label removed successfully' => 'Birka noņemta',
    'Status' => 'Statuss',
    'Add Label' => 'Pievienot birku',
    'Attach Label to actual record' => 'Pirvienot birku aktuālajam ierakstam',
    'User ID' => 'User ID',
    'auto' => 'auto',
    'Record ID' => 'Record ID',
    'User' => 'User',
    'Regexp' => 'Regexp',
    'Explode Time' => 'Explode Time',
    'Time' => 'Time',
    'manual' => 'manual',
    'Name' => 'Name',
    'Can not delete system labels(A)' => 'Can not delete system labels(A)',
    'Model Record ID' => 'Model Record ID',
    'Can not delete system labels' => 'Can not delete system labels',
    'Sys Company ID' => 'Sys Company ID',
    'ID' => 'ID',
    'Action Method' => 'Action Method',
    'Definition ID' => 'Definition ID',
    'Model record' => 'Model record',
    'Notes' => 'Notes',
    'Model ID' => 'Model ID',
    'Label/Time Bomb record' => 'Label/Time Bomb record',
    'Definition' => 'Definition',
    'D3labelsD3lLabelView' => 'D3labelsD3lLabelView',
    'Code' => 'Code',
    'D3labelsD3lLabelFull' => 'D3labelsD3lLabelFull',
    'Type' => 'Type',
    'D3labelsD3lLabelEdit' => 'D3labelsD3lLabelEdit',
    'Model' => 'Model',
    'Action Class' => 'Action Class',
    'Can not delete system labels(B)' => 'Can not delete system labels(B)',
    'Edit saved' => 'Izmaiņas saglabātas',
    'Save' => 'Saglabāt',
    'You do not have rights for removing label "{labelName}"' => 'Jums nav tiesību noņemt birku "{labelName}"',
    'Added' => 'Pievienoja birku',
    'Droped' => 'Noņēma birku',
    'Add label "{label}"' => 'Pievienot birku "{label}"',
    'Label "{labelOfLabel}" added to {cnt} records' => 'Birka "{labelOfLabel}" pievienota {cnt} ierakstiem',
    'Label "{labelOfLabel}" is not attached to any record' => 'Birka "{labelOfLabel}" nav pievienota neveinam ierakstam'
];
