<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Action' => 'Darbība',
    'Assigned Labels' => 'Piesaistītās birkas',
    'Attach' => 'Piesaistīt',
    'Attached' => 'Piesaistīta',
    'Cannot delete Label record' => 'Neizdevās noņemt birku',
    'Create Label' => 'Izveidot birku',
    'Collor' => 'Krāsa',
    'Cannot delete.  Attached to records' => 'Nav iespējams dzēst. Šī birka ir piesaistīta ierakstiem',
    'Deleted sucessfully' => 'Veiksmīgi dzēsta',
    'Existing Labels' => 'Izveidotās birkas',
    'Not exists or deleted already' => 'Neeksistē vai jau ir dzēsta',
    'Filter by Label' => 'Atlasīt pēc birkas',
    'Icon' => 'Ikona',
    'Labels created successfully' => 'Birka izveidota',
    'Label' => 'Nosaukums',
    'Label with this name exists already' => 'Birka ar šādu nosaukumu jau ir izveidota',
    'Labels' => 'Birkas',
    'Remove' => 'Noņemt',
    'Removed' => 'Noņemta',
    'Label removed sucessfully' => 'Birka noņemta',
    'Status' => 'Statuss',
    'Title' => 'Nosaukums',
    'Unable to create Label' => 'Neizdevās izveidot Birku',
];
